Final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp.views import file_list, upload_file, file_detail, file_convert, file_visualize, plot_img, db_list, setup_sql_db, store_s3
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', file_list, name='file_list'),
    path('dblist/', db_list, name='db_list'),
    path('upload/', upload_file, name='upload_file'),
    path('uploads/<int:pk>/', file_detail, name='file_detail'),
    path('convert/<int:pk>/', file_convert, name='file_convert'),
    path('visualize/<int:pk>/', file_visualize, name='file_visualize'),
    path('plot/', plot_img, name='plot_img'),
    path('sqlform/', setup_sql_db, name='setup_sql_db'),
    path('success/<str:pk>/', store_s3, name='store_s3'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
import os
from django.db import models

class UploadedFile(models.Model):
    file = models.FileField(upload_to='uploads/')
    local_file_type = models.CharField(max_length=10, choices=(('null','----'),('json', 'JSON'), ('csv', 'CSV'), ('image', 'Image'), ('pdf', 'Document')), blank=True, null=True)
    url_file_type = models.CharField(max_length=10, choices=(('null','----'),('sql', 'SQL'), ('nosql', 'NOSQL')),blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    file_url = models.CharField(max_length=255, blank=True, null=True)
    username = models.CharField(max_length=255, blank=True, null=True)
    password = models.CharField(max_length=255, blank=True, null=True)

    sql_db_connection =models.CharField(max_length=255, blank=True, null=True)
    sql_db_name =models.CharField(max_length=255, blank=True, null=True)
    sql_username =models.CharField(max_length=255, blank=True, null=True)
    sql_password =models.CharField(max_length=255, blank=True, null=True)



    conversion_type = models.CharField(max_length=10, choices=(('TimeSeries', 'Time Series'), ('ToSQL', 'To SQL'), ('LinearReg', 'Linear Regression')), blank=True, null=True)
    convert_type = models.CharField(max_length=10, choices=(('ToSQL', 'To SQL'), ('ToNOSQL', 'To NOSQL')), blank=True, null=True)

    collection_name_sql = models.CharField(max_length=255, blank=True, null=True)
    collection_name_nosql = models.CharField(max_length=255, blank=True, null=True)

    X_axis = models.CharField(max_length=255, blank=True, null=True)
    Y_axis = models.CharField(max_length=255, blank=True, null=True)

    mavg_column_name = models.CharField(max_length=255, blank=True, null=True)
    lags_column_name = models.CharField(max_length=255, blank=True, null=True)
    leads_column_name = models.CharField(max_length=255, blank=True, null=True)
    rolling_column_name = models.CharField(max_length=255, blank=True, null=True)
    timereg_column_name = models.CharField(max_length=255, blank=True, null=True)
    arima_column_name = models.CharField(max_length=255, blank=True, null=True)

    lags_data_column_name = models.CharField(max_length=255, blank=True, null=True)
    leads_data_column_name = models.CharField(max_length=255, blank=True, null=True)
    rolling_data_column_name = models.CharField(max_length=255, blank=True, null=True)
    timereg_data_column_name = models.CharField(max_length=255, blank=True, null=True)
    arima_data_column_name = models.CharField(max_length=255, blank=True, null=True)
    window = models.IntegerField(blank=True, null=True)
    lag_amt = models.IntegerField(blank=True, null=True)
    lead_amt = models.IntegerField(blank=True, null=True)
    roll_amt = models.IntegerField(blank=True, null=True)
    lag1_amt = models.IntegerField(blank=True, null=True)
    lag2_amt = models.IntegerField(blank=True, null=True)
    p_value = models.IntegerField(blank=True, null=True)
    q_value = models.IntegerField(blank=True, null=True)
    d_value = models.IntegerField(blank=True, null=True)



    # def __str__(self):
    #     retString = ""
    #     if self.file:
    #         retString += str(self.file)
    #     else:
    #         retString += "None"
    #     print(f"{retString}")


    def save(self, *args, **kwargs):
        self.local_file_type = self.get_file_type(self.file.name)
        super(UploadedFile, self).save(*args, **kwargs)

    def get_file_type(self, filename):
        ext = os.path.splitext(filename)[1].lower()
        if ext == '.csv':
            return 'csv'
        elif ext == '.json':
            return 'json'
        elif ext in ('.jpg', '.jpeg', '.png', '.gif'):
            return 'image'
        else:
            return 'unknown'

myapp/forms.py
from django import forms
from .models import UploadedFile

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ('file','local_file_type', 'url_file_type')
        widgets = {
            'file': forms.ClearableFileInput(attrs={'multiple': True}),
        }
# class UploadFileForm(forms.ModelForm):
#     class Meta:
#         model = UploadedFile
#         fields = ('file','file_type', 'file_url')

myapp/views.py
import csv
import json
import pandas as pd
from django.shortcuts import render, redirect,  get_object_or_404
from statsmodels.tsa.arima.model import ARIMA
from .forms import UploadFileForm
from .models import UploadedFile
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import os
import io
import numpy as np
import matplotlib.pyplot as plt
import zipfile
from django.urls import reverse
from datetime import datetime
import boto3



def store_s3(request, pk):
    aws_access_key_id = 'AKIA4W7FFVFRKSJIONJW'
    aws_secret_access_key = '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'
    region_name = 'us-east-1'
    bucket_name= 'b2photohw2'

    s3 = boto3.client('s3',
                    aws_access_key_id=aws_access_key_id,
                    aws_secret_access_key=aws_secret_access_key,
                    region_name=region_name)
    media_path = settings.MEDIA_ROOT
    url=media_path + "\\" + pk+"."+"zip"
    print(url)
    with open(url, 'rb') as file:
        s3.put_object(Bucket=bucket_name, Key=pk+"."+"zip", Body=file)


    return render(request, 'store_s3.html')


def sma_csv(cols, window_size):   
    # spark = SparkSession.builder.appName("LoadData").getOrCreate()
    # df = spark.read.csv(db, header=True, inferSchema=True)

    

    # print(db)
    # return cols, window_size
    # time_rows = df.select(cols).collect()
    # time = [row[cols] for row in time_rows]
    print(cols)
    time=cols
    l = len(time)
    sma = np.cumsum(time, dtype=float)
    sma[window_size:] = sma[window_size:] - sma[:-window_size]
    sma = sma[window_size - 1:] / window_size
    sma = sma.tolist()
    for i in range(0,l-len(sma)):
        sma.insert(0,None)
    x=[i for i in range(1,len(sma)+1)]
    y=sma
    return x,y

def arima(series,p,q,d):
    model = ARIMA(series, order=(p, q, d))
    result = model.fit()
    print(result.summary())
    predictions = result.predict(start=0, end=len(series)-1)
    x=[i for i in range(1,len(predictions)+1)]
    return x,predictions


def file_visualize(request, pk):
    print(request.POST)
    file = get_object_or_404(UploadedFile, pk=pk)

    content = file.file.read().decode('utf-8')
    csv_reader = csv.reader(io.StringIO(content))
    
    if request.method ==  'POST':
        print("post", request.POST['conversion_type'])
        if (request.POST['conversion_type']== 'TimeSeries'):
                if (request.POST['model_type']== 'MovingAvg'):
                    column_list = []
                    header = next(csv_reader) 
                    print(header) 
                    ind = header.index(request.POST['mavg_column_name'])
                    for row in csv_reader:
                        column_list.append(float(row[ind]))
                    column_list=column_list[1:]
                    x,y = sma_csv(column_list,int(request.POST['window']))
                    generate_plot(x,column_list,y)  
                
                if (request.POST['model_type']== 'Arima'):
                    p=int(request.POST['p_value'])
                    d=int(request.POST['d_value'])
                    q=int(request.POST['q_value'])
                    col = request.POST['arima_column_name']
                    data_col = request.POST['arima_data_column_name']

                    column_list = []
                    header = next(csv_reader) 
                    print(header) 
                    ind = header.index(col)
                    for row in csv_reader:
                        column_list.append(float(row[ind]))
                    column_list=column_list[1:]
                    x,y = arima(column_list,p,q,d)
                    generate_plot(x,column_list,y) 


                  
        form = UploadFileForm(request.POST, request.FILES)  
            
        return redirect('plot_img')
        # return redirect('file_detail', pk)
        
    else:
        form = UploadFileForm()
    # return render(request, 'upload_file.html', {'form': form})
    return render(request, 'file_visualize.html', {'file': file,'form': form })

def file_list(request):
    files = UploadedFile.objects.all()
    media_path = settings.MEDIA_ROOT
    dirs=[]
    for (dirpath, dirnames, filenames) in os.walk(media_path):
        if os.path.basename(dirpath).endswith(".zip"):
            # Ignore zip folders
            continue
        for dir_name in dirnames:
            if not dir_name.endswith(".zip"):
                dir_path = os.path.join(dirpath, dir_name)
                dir_time = datetime.fromtimestamp(os.path.getmtime(dir_path))
                dir_time = dir_time.strftime('%b %d, %Y %H:%M:%S')
                dirs.append({'name': dir_name, 'url': dir_path, 'size': '-', 'time': dir_time, 'type': 'directory'})
    print(dirs)

    return render(request, 'file_list.html', {'files': files, 'dirs':dirs})

def db_list(request):
    files = UploadedFile.objects.all()
    return render(request, 'db_list.html', {'files': files})

def generate_plot(x,y1,y2):
    if y2==None:
        plt.plot(x,y1)
        file_path = os.path.join(settings.MEDIA_ROOT, 'plot.png')
        plt.savefig(file_path)   
        plt.clf()
    else:
        plt.plot(x,y1)
        plt.plot(x,y2)
        file_path = os.path.join(settings.MEDIA_ROOT, 'plot.png')
        plt.savefig(file_path)   
        plt.clf()
     # fs = FileSystemStorage(location=settings.MEDIA_ROOT)
    # filename = fs.save("plot1.png", img)


def setup_sql_db(request):
    # print(request.POST)
    print(request.POST)
    if request.method == 'POST':
        print("inside post")
         
        return redirect('db_list')



    return render(request, 'setup_sql_db.html')



def upload_file(request):
    # form = None
    print(request.POST)
    # print("abc")
    if request.method == 'POST':
        print("post", request.POST['upload_option'])
        if 'local' == request.POST['upload_option']:
            
            form = UploadFileForm(request.POST, request.FILES)
            # print("local", form, form.is_valid())
            if form.is_valid():
                print("form is valid")
                file_type = form.cleaned_data['local_file_type']
                if(file_type == 'image'):
                    uploaded_file = request.FILES['file']
                    print(uploaded_file)
                    fs = FileSystemStorage(location=settings.MEDIA_ROOT)
                    with zipfile.ZipFile(uploaded_file, 'r') as zip_ref:
                        zip_ref.extractall(settings.MEDIA_ROOT)
                    filename = fs.save(uploaded_file.name, uploaded_file)
                    file_url = fs.url(filename)
                    # uploaded_file_obj = UploadedFile(file=filename, local_file_type=file_type)
                    # uploaded_file_obj.save()
                    

                else:
                    file_type = form.cleaned_data['local_file_type']
                    uploaded_file = request.FILES['file']
                    fs = FileSystemStorage(location=settings.MEDIA_ROOT)
                    filename = fs.save(uploaded_file.name, uploaded_file)
                    file_url = fs.url(filename)
                    print(file_url)
                    uploaded_file_obj = UploadedFile(file=filename, local_file_type=file_type)
                    uploaded_file_obj.save()

                    # if (request.POST['conversion_type']== 'TimeSeries'):
                    #     if (request.POST['model_type']== 'MovingAvg'):
                    #         print(sma(file_url,request.POST['mavg_column_name'],int(request.POST['window'])))
                    #         x=[1,2,3,4,5]
                    #         y=[10,20,30,40,50]
                    #         generate_plot(x,y)


                print(request.POST['local_file_type'])
                return redirect('file_list')
        elif 'url' == request.POST['upload_option']:
            print("url")
            url = request.POST['file_url']
            file_type = request.POST['url_file_type']
            username = request.POST['username']
            password = request.POST['password']
            print(username)
            # uploaded_file_obj = UploadedFile(file=url, url_file_type=file_type)
            # uploaded_file_obj.save()
            return redirect('file_list')
    else:
        form = UploadFileForm()
    return render(request, 'upload_file.html', {'form': form})

# def upload_file(request):
#     if request.method == 'POST':
#         form = UploadFileForm(request.POST, request.FILES)
#         if form.is_valid():
#             file_type = form.cleaned_data['file_type']
#             print(file_type)
#             uploaded_file = request.FILES['file']
#             fs = FileSystemStorage(location=settings.MEDIA_ROOT)
#             filename = fs.save(uploaded_file.name, uploaded_file)
#             file_url = fs.url(filename)
#             uploaded_file_obj = UploadedFile(file=filename, file_type=file_type)
#             uploaded_file_obj.save()
#             return redirect('file_list')
#     else:
#         form = UploadFileForm()
#     return render(request, 'upload_file.html', {'form': form})


def file_detail(request, pk):
    file = get_object_or_404(UploadedFile, pk=pk)
    if file.local_file_type == 'csv':
        # content = file.file.read().decode('ISO-8859-1')
        # # use pandas to read the CSV data and create a DataFrame
        # df = pd.read_csv(io.StringIO(content))
        # # convert the DataFrame to an HTML table
        # table = df.to_html(index=False)
        # return render(request, 'file_detail.html', {'file': file, 'table': table})
        content = file.file.read().decode('utf-8')
        reader = csv.reader(io.StringIO(content), delimiter=';')
        rows = [row for row in reader]
        # print(rows)
        print(file.local_file_type)
        return render(request, 'file_detail.html', {'file': file, 'rows': rows})
    # elif file.file_type in ['jpg', 'jpeg', 'png', 'gif']:
    else:

myapp/templates/file_convert.html
{% extends 'base.html' %}

{% block content %}
  <h2>Convert File</h2>

  {% if file.local_file_type == 'csv' %}

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    

        <!-- <div id="image_upload" style="display:none">
          <label for="conversion">Choose Operation:</label>
          <select name="conversion_type" id="conversion_type" onchange="csvtypeOption(this.value)">
            <option value="TimeSeries">Time Series</option>
            <option value="ToSQL">To SQL</option>
            <option value="LinearReg">Linear Regression</option>
          </select>
          </div> -->

        <!-- <div id="csv_div" style="display:none"> -->


        <div id="csv_options" >
        <label for="conversion">Choose Operation:</label>
        <select name="convert_type" id="conversion_type" onchange="csvtypeOption(this.value)">
          <!-- <option value="TimeSeries">Time Series</option> -->
          <option value="ToSQL">To SQL</option>
          <option value="ToNOSQL">To NOSQL</option>

          <!-- <option value="LinearReg">Linear Regression</option> -->
        </select>
        </div>

        <div id="sql" style="display:none">
          <label for="collection">Collection Name:</label>
          <input type="text" name="collection_name_sql" placeholder="Enter sql Collection name">
        </div>

        <div id="nosql" style="display:none">
          <label for="collection">Collection Name:</label>
          <input type="text" name="collection_name_nosql" placeholder="Enter nosql Collection name">
        </div>

       
        

       

        
    <!-- </div> -->
        

        <br><br>
        <!-- <input type="file" name="file"> -->
        <button type="submit">Submit</button>
      </div>
    <!-- <div id="url-upload" style="display:none">
        <label for="id_url_file_type">File type:</label>
        <select name="url_file_type" id="id_url_file_type">
            <option value="null">----</option>
            <option value="sql">SQL</option>
            <option value="nosql">NOSQL</option>
        </select>
        <br><br>
        <input type="text" name="file_url" placeholder="Enter file URL">
        <input type="text" name="username" placeholder="Enter Username">
        <input type="text" name="password" placeholder="Enter Password">
    </div> -->
    <br><br>
  </form>

  {% else %}
        <!-- <p>abcd</p> -->
        <img src="{{ MEDIA_URL }}{{ file.file.url }}" alt="{{ file.name }}">
  {% endif %}
  
  <script>
    // document.getElementById("local-upload").style.display = "block";
    // document.getElementById("csv_options").style.display = "block";
    document.getElementById("sql").style.display = "block";
    // document.getElementById("moving_avg").style.display = "block";
    // document.getElementById("TS_div").style.display = "block";
    // document.getElementById("csv_div").style.display = "block";

    

      // function handleUploadOption(value) {
      //     if (value == "local") {
      //         document.getElementById("local-upload").style.display = "block";
      //         document.getElementById("url-upload").style.display = "none";
      //     } else {
      //         document.getElementById("local-upload").style.display = "none";
      //         document.getElementById("url-upload").style.display = "block";
      //     }
      // }

      // function FiletypeOption(value) {
      //     if (value == "csv") {
      //         document.getElementById("csv_div").style.display = "block";
      //         document.getElementById("csv_options").style.display = "block";

              
      //     } else {
      //       document.getElementById("csv_div").style.display = "none";

      //       document.getElementById("csv_options").style.display = "none";
      //     }
      // }

      function csvtypeOption(value) {
          if (value == "TOSQL") {
              // document.getElementById("time_series").style.display = "block";
              // document.getElementById("TS_div").style.display = "block";

              document.getElementById("sql").style.display = "block";
              document.getElementById("nosql").style.display = "none";

              // document.getElementById("linear_reg").style.display = "none";
              
          } 
          else{
              

              document.getElementById("sql").style.display = "none";
              document.getElementById("nosql").style.display = "block";

              // document.getElementById("linear_reg").style.display = "block";
          }
      }

      
  </script>
  
  
  
{% endblock %}

myapp/templates/image_detail.html
{% extends 'base.html' %}

{% block content %}
    <img src="{{ MEDIA_URL }}{{ file.file }}" alt="{{ file.name }}">
{% endblock %}

myapp/templates/plot_img.html
{% extends 'base.html' %}

{% block content %}
<img src="/media/plot.png" alt="rolling">
<!-- <img src="{{ MEDIA_URL }}plot.png" alt="{{ file.name }}"> -->
    
{% endblock %}

myapp/templates/upload_file.html
{% extends 'base.html' %}

{% block content %}
  <h2>Upload a File</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    <label for="id_upload_option">Upload option:</label>
    <select name="upload_option" id="id_upload_option" onchange="handleUploadOption(this.value)">
        <option value="local">Local</option>
        <option value="url">URL</option>
    </select>
    <br><br>
    <div id="local-upload" style="display:none">
        <label for="id_local_file_type">File type:</label>
        <select name="local_file_type" id="id_local_file_type" onchange="FiletypeOption(this.value)">
            <option value="csv">CSV</option>
            <option value="json">JSON</option>
            <option value="image">Image</option>
        </select>


        <div id="csv_options" style="display:none">
        <label for="conversion">Choose Operation:</label>
        <select name="conversion_type" id="conversion_type" onchange="csvtypeOption(this.value)">
          <option value="TimeSeries">Time Series</option>
          <option value="ToSQL">To SQL</option>
          <option value="LinearReg">Linear Regression</option>
        </select>
        </div>

        <div id="sql" style="display:none">
          <label for="collection">Collection Name:</label>
          <input type="text" name="collection_name" placeholder="Enter Collection name">
        </div>

        <div id="linear_reg" style="display:none">
          <label for="axisX">X-axis column name:</label>
          <input type="text" name="X_axis" placeholder="Enter X axis">
          <label for="axisY">Y-axis column name:</label>
          <input type="text" name="Y_axis" placeholder="Enter Y axis">
        </div>

        

        <div id="time_series" style="display:none">
          <label for="model">Choose Model:</label>
          <select name="model_type" id="model_type" onchange="TimeSeriesOption(this.value)">
            <option value="MovingAvg">Moving Average</option>
            <option value="Lags">Lags</option>
            <option value="Leads">Leads</option>
            <option value="Rolling">Rolling</option>
            <option value="TimeRegression">Time Regression</option>
            <option value="Arima">Arima</option>
          </select>
          </div>

        <div id="TS_div" style="display:none">

        <div id="moving_avg" style="display:none">
          <label for="col">Column name:</label>
          <input type="text" name="mavg_column_name" placeholder="Enter Column name">
          <br>
          <label for="window_size">Window size:</label>
          <input type="number" name="window" placeholder="Enter Window size">
        </div>

        <div id="lags" style="display:none">
          <label for="col">Column name:</label>
          <input type="text" name="lags_column_name" placeholder="Enter Column name"><br>
          <label for="datcol">Data column name:</label>
          <input type="text" name="lags_data_column_name" placeholder="Enter Data Column name"><br>
          <label for="lag">Lag Amount:</label>
          <input type="number" name="lag_amt" placeholder="Enter Lag amount">
        </div>

        <div id="leads" style="display:none">
          <label for="col">Column name:</label>
          <input type="text" name="leads_column_name" placeholder="Enter Column name"><br>
          <label for="datcol">Data column name:</label>
          <input type="text" name="leads_data_column_name" placeholder="Enter Data Column name"><br>
          <label for="lead">Lead Amount:</label>
          <input type="number" name="lead_amt" placeholder="Enter Lead amount">
        </div>

        <div id="rolling" style="display:none">
          <label for="col">Column name:</label>
          <input type="text" name="rolling_column_name" placeholder="Enter Column name"><br>
          <label for="datcol">Data column name:</label>
          <input type="text" name="rolling_data_column_name" placeholder="Enter Data Column name"><br>
          <label for="roll">Roll Amount:</label>
          <input type="number" name="roll_amt" placeholder="Enter Roll amount">
        </div>

        <div id="timereg" style="display:none">
          <label for="col">Column name:</label>
          <input type="text" name="timereg_column_name" placeholder="Enter Column name"><br>
          <label for="datcol">Data column name:</label>
          <input type="text" name="timereg_data_column_name" placeholder="Enter Data Column name"><br>
          <label for="lag1">lag1 Amount:</label>
          <input type="number" name="lag1_amt" placeholder="Enter lag1 amount"><br>
          <label for="lag2">lag2 Amount:</label>
          <input type="number" name="lag2_amt" placeholder="Enter lag2 amount">
        </div>

        <div id="arima" style="display:none">
          <label for="col">Column name:</label>
          <input type="text" name="arima_column_name" placeholder="Enter Column name"><br>
          <label for="datcol">Data column name:</label>
          <input type="text" name="arima_data_column_name" placeholder="Enter Data Column name"><br>
          <label for="p">p value:</label>
          <input type="number" name="p_value" placeholder="Enter p value"><br>
          <label for="q">q value:</label>
          <input type="number" name="q_value" placeholder="Enter q value"><br>
          <label for="d">d value:</label>
          <input type="number" name="d_value" placeholder="Enter d value">
        </div>
      </div>
        

        <br><br>
        <input type="file" name="file">
    </div>
    <div id="url-upload" style="display:none">
        <label for="id_url_file_type">File type:</label>
        <select name="url_file_type" id="id_url_file_type">
            <option value="sql">SQL</option>
            <option value="nosql">NOSQL</option>
        </select>
        <br><br>
        <input type="text" name="file_url" placeholder="Enter file URL">
        <input type="text" name="username" placeholder="Enter Username">
        <input type="text" name="password" placeholder="Enter Password">
    </div>
    <br><br>
    <button type="submit">Upload</button>
  </form>
  
  <script>
    document.getElementById("local-upload").style.display = "block";
    document.getElementById("csv_options").style.display = "block";
    document.getElementById("time_series").style.display = "block";
    document.getElementById("moving_avg").style.display = "block";
    document.getElementById("TS_div").style.display = "block";

    

      function handleUploadOption(value) {
          if (value == "local") {
              document.getElementById("local-upload").style.display = "block";
              document.getElementById("url-upload").style.display = "none";
          } else {
              document.getElementById("local-upload").style.display = "none";
              document.getElementById("url-upload").style.display = "block";
          }
      }

      function FiletypeOption(value) {
          if (value == "csv") {
              document.getElementById("csv_options").style.display = "block";
              
          } else {
            document.getElementById("csv_options").style.display = "none";
          }
      }

      function csvtypeOption(value) {
          if (value == "TimeSeries") {
              document.getElementById("time_series").style.display = "block";
              document.getElementById("TS_div").style.display = "block";

              document.getElementById("sql").style.display = "none";
              document.getElementById("linear_reg").style.display = "none";
              
          } else if (value == "ToSQL")
          {
              document.getElementById("time_series").style.display = "none";
              document.getElementById("TS_div").style.display = "none";

              document.getElementById("sql").style.display = "block";
              document.getElementById("linear_reg").style.display = "none";
          }
          else{
              document.getElementById("time_series").style.display = "none";
              document.getElementById("TS_div").style.display = "none";

              document.getElementById("sql").style.display = "none";
              document.getElementById("linear_reg").style.display = "block";
          }
      }

      function TimeSeriesOption(value) {
          if (value == "MovingAvg") {
              document.getElementById("moving_avg").style.display = "block";
              document.getElementById("lags").style.display = "none";
              document.getElementById("leads").style.display = "none";
              document.getElementById("rolling").style.display = "none";
              document.getElementById("timereg").style.display = "none";
              document.getElementById("arima").style.display = "none";

          } else if (value == "Lags")
          {
              document.getElementById("moving_avg").style.display = "none";
              document.getElementById("lags").style.display = "block";
              document.getElementById("leads").style.display = "none";
              document.getElementById("rolling").style.display = "none";
              document.getElementById("timereg").style.display = "none";
              document.getElementById("arima").style.display = "none";
          } else if (value == "Leads")
          {
              document.getElementById("moving_avg").style.display = "none";
              document.getElementById("lags").style.display = "none";
              document.getElementById("leads").style.display = "block";
              document.getElementById("rolling").style.display = "none";
              document.getElementById("timereg").style.display = "none";
              document.getElementById("arima").style.display = "none";
          } else if (value == "Rolling")
          {
              document.getElementById("moving_avg").style.display = "none";
              document.getElementById("lags").style.display = "none";
              document.getElementById("leads").style.display = "none";
              document.getElementById("rolling").style.display = "block";
              document.getElementById("timereg").style.display = "none";
              document.getElementById("arima").style.display = "none";
          } else if (value == "TimeRegression")
          {
              document.getElementById("moving_avg").style.display = "none";
              document.getElementById("lags").style.display = "none";
              document.getElementById("leads").style.display = "none";
              document.getElementById("rolling").style.display = "none";
              document.getElementById("timereg").style.display = "block";
              document.getElementById("arima").style.display = "none";
          }
          else{
              document.getElementById("moving_avg").style.display = "none";
              document.getElementById("lags").style.display = "none";
              document.getElementById("leads").style.display = "none";
              document.getElementById("rolling").style.display = "none";
              document.getElementById("timereg").style.display = "none";
              document.getElementById("arima").style.display = "block";
          }
      }
  </script>
{% endblock %}